version: '3'

services:
  nginx:
    container_hostname: nginx
    hostname: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 9999:9999
    volumes:
      - /home/pi/Documents/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
